/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserRolesView': RouteRecordInfo<'/admin/AdminUserRolesView', '/admin/AdminUserRolesView', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/DeleteUserDialog': RouteRecordInfo<'/admin/components/dialogs/DeleteUserDialog', '/admin/components/dialogs/DeleteUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/EditUserDialog': RouteRecordInfo<'/admin/components/dialogs/EditUserDialog', '/admin/components/dialogs/EditUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/UserDetailsDialog': RouteRecordInfo<'/admin/components/dialogs/UserDetailsDialog', '/admin/components/dialogs/UserDetailsDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/membership/dialogs/AddMemberDialog': RouteRecordInfo<'/admin/components/membership/dialogs/AddMemberDialog', '/admin/components/membership/dialogs/AddMemberDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/membership/dialogs/AddPaymentDialog': RouteRecordInfo<'/admin/components/membership/dialogs/AddPaymentDialog', '/admin/components/membership/dialogs/AddPaymentDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/membership/dialogs/DeletePaymentDialog': RouteRecordInfo<'/admin/components/membership/dialogs/DeletePaymentDialog', '/admin/components/membership/dialogs/DeletePaymentDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/membership/dialogs/EditPaymentDialog': RouteRecordInfo<'/admin/components/membership/dialogs/EditPaymentDialog', '/admin/components/membership/dialogs/EditPaymentDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/membership/dialogs/PaymentHistoryDialog': RouteRecordInfo<'/admin/components/membership/dialogs/PaymentHistoryDialog', '/admin/components/membership/dialogs/PaymentHistoryDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/membership/MemberDetailsTable': RouteRecordInfo<'/admin/components/membership/MemberDetailsTable', '/admin/components/membership/MemberDetailsTable', Record<never, never>, Record<never, never>>,
    '/admin/components/membership/MembershipTypeCard': RouteRecordInfo<'/admin/components/membership/MembershipTypeCard', '/admin/components/membership/MembershipTypeCard', Record<never, never>, Record<never, never>>,
    '/admin/components/membership/payment/PaymentSummaryCard': RouteRecordInfo<'/admin/components/membership/payment/PaymentSummaryCard', '/admin/components/membership/payment/PaymentSummaryCard', Record<never, never>, Record<never, never>>,
    '/admin/components/SearchBar': RouteRecordInfo<'/admin/components/SearchBar', '/admin/components/SearchBar', Record<never, never>, Record<never, never>>,
    '/admin/components/UserManagementTable': RouteRecordInfo<'/admin/components/UserManagementTable', '/admin/components/UserManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/dialogs/AdminUserRolesDialog', '/admin/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/UserManagementView': RouteRecordInfo<'/admin/UserManagementView', '/admin/UserManagementView', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/components/landing/AboutSection': RouteRecordInfo<'/components/landing/AboutSection', '/components/landing/AboutSection', Record<never, never>, Record<never, never>>,
    '/components/landing/FeaturesSection': RouteRecordInfo<'/components/landing/FeaturesSection', '/components/landing/FeaturesSection', Record<never, never>, Record<never, never>>,
    '/components/landing/HeroSection': RouteRecordInfo<'/components/landing/HeroSection', '/components/landing/HeroSection', Record<never, never>, Record<never, never>>,
    '/components/landing/StatsSection': RouteRecordInfo<'/components/landing/StatsSection', '/components/landing/StatsSection', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/otherTab/Page1View': RouteRecordInfo<'/otherTab/Page1View', '/otherTab/Page1View', Record<never, never>, Record<never, never>>,
  }
}
